### ISSUE TITLE
Improve ci.yml templating with reusable actions

### ISSUE THREAD

**Issue by andeaseme** [i2mint/isee#18]
All github CI's have some version of `uses: actions/checkout@v3`. The [`uses`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses) keyword selects an action to run as part of a step in your job. An action is a reusable unit of code. You can use an action defined in the same repository as the workflow, a public repository, or in a published Docker container image. 

You can set input parameters specific to the repo using the [`with`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) keyword. [Here is a list of allowed inputs from actions/checkout.](https://github.com/actions/checkout#usage)

We can create on of these actions for docs and publishing to use across all repos without the copy paste method and allow for much easier updating of ci.yml and version control over CI scripts.

This issue is a follow up on the changes to move compiled docs to it's own branch: https://github.com/i2mint/epythet/issues/12

**Comment by thorwhalen** [comment]
Is this related to being able to "safely" make changes to CI configs in bulk when these CI configs may share some code through templating, but also have some other specifics that we don't want to lose in a bulk edit? 

If so, it's also related to the example (second paragraph) in [issue 1 of config2py](https://github.com/i2mint/config2py/issues/1).

But though the pattern (that `configs2py` would like to take care of when it grows up) is common in many other situations besides CI, I'd prefer to use some specific CI tool like you mention if available. At least at this point.

**Comment by andeaseme** [comment]
GitHub Actions can be used to update and maintain CI workflows from a single source rather than at each repo.

See [Publishing to GitHub Page with GitHub Actions](https://github.com/i2mint/epythet#publishing-to-github-page-with-github-actions) and recent [changes to Epythet](https://github.com/i2mint/epythet/compare/0.0.73...0.0.79) for example of how the process of deploying GitHub Pages can be maintained in the Epythet repo and reused in other repos.
